AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Mentareeding App

  Mentareeding SPA
  
Globals:
  Function:
    Timeout: 10

Resources:
  MentareedingAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      MemorySize: 256
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HttpEvent:
          Type: HttpApi
    Metadata:
      DockerTag: v1
      DockerContext: ./app
      Dockerfile: Dockerfile
      
Outputs:
  MentareedingAppFunctionURL:
    Description: "API Gateway endpoint URL for Next.js"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
